In [1]:
import importlib
import argparse
import os
import torch

In [2]:
def parse_args():
    parser = argparse.ArgumentParser('Model')
    parser.add_argument('--model', type=str, default='pointnet2_sem_seg', help='model name [default: pointnet_sem_seg]')
    parser.add_argument('--batch_size', type=int, default=16, help='Batch Size during training [default: 16]')
    parser.add_argument('--epoch', default=32, type=int, help='Epoch to run [default: 32]')
    parser.add_argument('--learning_rate', default=0.001, type=float, help='Initial learning rate [default: 0.001]')
    parser.add_argument('--gpu', type=str, default='0', help='GPU to use [default: GPU 0]')
    parser.add_argument('--optimizer', type=str, default='Adam', help='Adam or SGD [default: Adam]')
    parser.add_argument('--log_dir', type=str, default=None, help='Log path [default: None]')
    parser.add_argument('--decay_rate', type=float, default=1e-4, help='weight decay [default: 1e-4]')
    parser.add_argument('--npoint', type=int, default=4096, help='Point Number [default: 4096]')
    parser.add_argument('--step_size', type=int, default=10, help='Decay step for lr decay [default: every 10 epochs]')
    parser.add_argument('--lr_decay', type=float, default=0.7, help='Decay rate for lr decay [default: 0.7]')
    parser.add_argument('--test_area', type=int, default=5, help='Which area to use for test, option: 1-6 [default: 5]')

    return parser.parse_args()

In [3]:
from pointnet.models.pointnet2_sem_seg import get_model

classifier = get_model(6).cuda()#

In [4]:
# print classifiers parameters
num_params = 0
for param in classifier.parameters():
    num_params += param.numel()
print('Total number of parameters: %d' % num_params)

Total number of parameters: 967366


In [13]:
input = torch.rand(1, 9, 2048).cuda()*2 - 0.5
input2 = input.clone()
classifier.train()
pred, label = classifier(input)
classifier.eval()
pred2, label2 = classifier(input)


In [14]:
print(input)
print(torch.all(input.permute(0, 2, 1) == input.transpose(2,1)))

tensor([[[-0.3663, -0.2715,  0.9893,  ..., -0.0030,  0.4206,  1.3122],
         [ 0.9964, -0.2330,  1.2851,  ...,  0.1651,  0.9246,  1.1202],
         [ 0.2094,  0.1582,  0.4718,  ...,  0.5509,  0.3841,  0.7598],
         ...,
         [-0.4682,  0.5770,  0.2329,  ...,  0.4164,  0.3356,  0.2888],
         [ 0.3728,  0.1340,  0.7693,  ...,  0.3844,  0.5648, -0.3686],
         [-0.3690,  0.1667,  0.8422,  ...,  1.1495,  0.6075,  0.4641]]],
       device='cuda:0')


In [15]:
print(pred)

tensor([[[-0.0589, -0.1485,  0.5383,  1.1014,  0.7698,  1.0260],
         [-0.1359,  0.1432,  0.3226,  0.2641,  0.5689, -0.7654],
         [ 0.7686, -0.2590,  1.3068, -0.1296,  0.4115,  0.7746],
         ...,
         [ 0.1930,  0.3330,  0.6197, -0.0708,  0.8040,  0.6911],
         [-0.3145, -0.7046,  0.2097,  0.2600,  0.3233, -0.1273],
         [ 0.4389, -0.1210, -0.2671,  0.3203, -0.1259, -0.1397]]],
       device='cuda:0', grad_fn=<PermuteBackward0>)


In [16]:
print(pred2)

tensor([[[ 0.0383,  0.0146, -0.0180,  0.0098,  0.0209,  0.0997],
         [ 0.0384,  0.0149, -0.0177,  0.0101,  0.0209,  0.1000],
         [ 0.0385,  0.0145, -0.0180,  0.0099,  0.0209,  0.0998],
         ...,
         [ 0.0385,  0.0150, -0.0177,  0.0101,  0.0208,  0.0998],
         [ 0.0383,  0.0149, -0.0177,  0.0100,  0.0209,  0.0998],
         [ 0.0383,  0.0143, -0.0181,  0.0097,  0.0208,  0.0997]]],
       device='cuda:0', grad_fn=<PermuteBackward0>)
